# Generated by Django 5.0.3 on 2024-03-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subtopic",
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.RemoveField(
            model_name="subtopic",
            name="slug",
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
