# Generated by Django 5.0.3 on 2024-06-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_alter_choice_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="text",
            field=models.CharField(max_length=75),
        ),
    ]
