# Generated by Django 5.0.3 on 2024-07-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0008_alter_subtopic_name_alter_topic_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtopic",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
