# Generated by Django 5.0.3 on 2024-08-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0009_alter_subtopic_name_alter_topic_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtopic",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
