# Generated by Django 5.0.3 on 2025-01-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0010_alter_subtopic_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(),
        ),
    ]
