# Generated by Django 5.0.3 on 2025-02-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0012_alter_choice_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
    ]
