# Generated by Django 5.0.3 on 2024-11-19 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "residency_program",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pg_level", models.CharField(blank=True, max_length=10, null=True)),
                ("cell_phone", models.CharField(blank=True, max_length=15, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
